# Generated by Django 6.0.1 on 2026-02-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='scanned_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
