# Generated by Django 6.0.1 on 2026-02-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_add_scanned_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='image_fingerprint',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
