# Generated by Django 6.0.1 on 2026-02-22 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanresult_image_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('calories', models.FloatField(default=0)),
                ('kilojoules', models.FloatField(default=0)),
                ('ingredients', models.JSONField(default=list)),
                ('generated_image', models.TextField(blank=True, default='')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_dishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
