# Generated by Django 6.0.1 on 2026-02-21 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('dish_name', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('carbs_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_logs', to='scanner.scanresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('goal', models.CharField(max_length=50)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('weekly_pace_kg', models.FloatField(default=0.5)),
                ('activity_level', models.CharField(max_length=50)),
                ('diet_type', models.CharField(default='Normal', max_length=20)),
                ('daily_calories', models.IntegerField(default=2000)),
                ('daily_protein_g', models.IntegerField(default=150)),
                ('daily_carbs_g', models.IntegerField(default=200)),
                ('daily_fat_g', models.IntegerField(default=65)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.JSONField(default=dict)),
                ('lunch', models.JSONField(default=dict)),
                ('dinner', models.JSONField(default=dict)),
                ('snacks', models.JSONField(default=list)),
                ('total_calories', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
